---
language: ruby
rvm:
- 2.0.0
services:
- redis-server
- postgresql

script: 
- bundle exec rake --trace

before_script:
- psql -c 'create database gistr_test;' -U postgres

after_success:
- bash -x -e bin/travis-deploy.sh

env:
  global:
  - secure: |-
      OttEShBYWrpZ4Bv6MF5teSAld5OdXMmZ17XHhbCgbWXvYfFM5ciXwDARmuaN
      NiMIk0Bxt64iGSeUk+VerU1hZejL06LZtdeNN9tGLVpqOqEbwaFHWy6K3QpJ
      mU4oGncZ4YPbVXSXya04KGWLx0AM8KRB3mX9EvB0hMvin1NRiSE=
