development:
  adapter: postgresql
  database: gistr
  pool: 5
  timeout: 5000


test:
  adapter: postgresql
  database: gistr-test
  user: postgres
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: db/production.sqlite3
  pool: 5
  timeout: 5000
