development:
  adapter: postgresql
  database: gistr
  pool: 5
  timeout: 5000


test:
  adapter: postgresql
  database: gistr-test
  pool: 5
  timeout: 5000
  <% if ENV['TRAVIS'] %>
  user: postgres
  <% end %>

production:
  adapter: postgresql
  database: db/production.sqlite3
  pool: 5
  timeout: 5000
