development:
  host: <%= ENV['GISTR_REDIS_HOST'] || 'localhost' %>
  port: <%= ENV['GISTR_REDIS_PORT'] || '6379'      %>
  db:   <%= ENV['GISTR_REDIS_DB']   || '0'         %>

test:
  host: <%= ENV['GISTR_REDIS_HOST'] || 'localhost' %>
  port: <%= ENV['GISTR_REDIS_PORT'] || '6379'      %>
  db:   <%= ENV['GISTR_REDIS_DB']   || '1'         %>

production:
  host: <%= ENV['GISTR_REDIS_HOST'] %>
  port: <%= ENV['GISTR_REDIS_PORT'] %>
  db:   <%= ENV['GISTR_REDIS_DB']   %>